import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { dbConnect } from "@/db/dbConnection/dbConnection";
import Category from "@/components/auth/Category";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Category />
        {children}
      </body>
    </html>
  );
}
